// cases.js - 全球教育创新案例库数据文件
// 案例数据数组，共包含75个教育创新案例
const casesData = [
    // ========== 原有案例 (ID 1-8) ==========
    {
        id: 1,
        title: "德国双元制职业教育现代化改革",
        category: "vocational",
        country: "德国",
        description: "企业深度参与、标准化培训条例、跨企业培训中心的模式创新，实现了学校与企业的无缝对接。",
        impact: "青年失业率降至5.2%，企业满意度达87%，毕业生就业率达到94%",
        tags: ["职业教育", "校企合作", "德国模式"],
        color: "blue",
        icon: "fas fa-industry",
        stats: { satisfaction: 87, employment: 94, skillMatch: 76 }
    },
    {
        id: 2,
        title: "芬兰现象式学习（Phenomenon-based Learning）",
        category: "curriculum",
        country: "芬兰",
        description: "打破学科界限，以真实世界问题为核心组织课程内容，培养学生综合解决问题的能力。",
        impact: "学生问题解决能力提升35%，跨学科素养显著改善，创造力指数提高42%",
        tags: ["课程改革", "跨学科", "创新教学"],
        color: "purple",
        icon: "fas fa-lightbulb",
        stats: { satisfaction: 92, employment: 88, skillMatch: 85 }
    },
    {
        id: 3,
        title: "新加坡技能创前程（SkillsFuture）计划",
        category: "policy",
        country: "新加坡",
        description: "全民终身学习体系，政府资助个人技能提升，建立技能认证与职业发展衔接机制。",
        impact: "成人参与率62%，技能提升认证覆盖率75%，就业匹配度提高28%",
        tags: ["终身学习", "政策创新", "技能认证"],
        color: "green",
        icon: "fas fa-landmark",
        stats: { satisfaction: 85, employment: 90, skillMatch: 82 }
    },
    {
        id: 4,
        title: "加拿大体验式学习框架",
        category: "basic",
        country: "加拿大",
        description: "将工作体验融入基础教育，从幼儿园到高中阶段逐步引入职业探索与实践机会。",
        impact: "学生职业认知度提升56%，学习动机增强41%，辍学率降低23%",
        tags: ["基础教育", "职业探索", "实践学习"],
        color: "orange",
        icon: "fas fa-school",
        stats: { satisfaction: 88, employment: 86, skillMatch: 79 }
    },
    {
        id: 5,
        title: "日本超级全球化高中计划",
        category: "curriculum",
        country: "日本",
        description: "培养全球化领导力的特色高中，全英文授课，强化国际交流与合作项目。",
        impact: "学生英语能力提升73%，国际升学率65%，跨文化能力显著增强",
        tags: ["全球化", "特色学校", "语言教学"],
        color: "red",
        icon: "fas fa-globe",
        stats: { satisfaction: 84, employment: 89, skillMatch: 81 }
    },
    {
        id: 6,
        title: "澳大利亚职业教育与培训包体系",
        category: "vocational",
        country: "澳大利亚",
        description: "行业主导的能力标准开发，灵活的学习路径，全国统一的资格认证框架。",
        impact: "行业标准覆盖率95%，培训质量满意度88%，技能转化率72%",
        tags: ["职业标准", "灵活学习", "认证体系"],
        color: "blue",
        icon: "fas fa-certificate",
        stats: { satisfaction: 86, employment: 91, skillMatch: 78 }
    },
    {
        id: 7,
        title: "荷兰个性化学习路径",
        category: "basic",
        country: "荷兰",
        description: "基于学生能力与兴趣的个性化课程设计，灵活的学习进度安排与导师制支持。",
        impact: "学生参与度提升47%，学习效率提高39%，个性化支持满意度92%",
        tags: ["个性化", "灵活学习", "导师制"],
        color: "orange",
        icon: "fas fa-user-graduate",
        stats: { satisfaction: 91, employment: 85, skillMatch: 83 }
    },
    {
        id: 8,
        title: "韩国数字化转型教育战略",
        category: "digital",
        country: "韩国",
        description: "全面推动教育数字化，智慧校园建设，人工智能辅助教学，数字素养普及。",
        impact: "数字化教学覆盖率98%，教师数字素养提升65%，学生学习效率提高31%",
        tags: ["数字化", "人工智能", "智慧教育"],
        color: "cyan",
        icon: "fas fa-laptop-code",
        stats: { satisfaction: 83, employment: 87, skillMatch: 80 }
    },
    
    // ========== 新增国内案例 (ID 9-45) ==========
    {
        id: 9,
        title: "浙江温州工学一体化技能人才培养",
        category: "vocational",
        country: "中国",
        description: "系统构建'政企校研'协同的产教评生态链，创新'校中厂'、'厂中校'双轨模式，将企业真实项目融入教学全周期。",
        impact: "学生平均就业率达98.4%，为当地电气、鞋服等支柱产业输送逾10万名技能人才",
        tags: ["工学一体", "产教融合", "技能生态链"],
        color: "blue",
        icon: "fas fa-industry",
        stats: { satisfaction: 88, employment: 98, skillMatch: 90 }
    },
    {
        id: 10,
        title: "上海市义务教育小班化教学改革",
        category: "basic",
        country: "中国",
        description: "在中心城区部分学校打破'插秧式'传统课堂布局，通过物理空间改造、分组围坐、分层教学实现教师角色转变。",
        impact: "试点学校课堂互动质量和学生参与度显著提升，形成可复制的'上海经验'",
        tags: ["小班化", "因材施教", "课堂改革"],
        color: "orange",
        icon: "fas fa-users",
        stats: { satisfaction: 90, employment: 0, skillMatch: 85 }
    },
    {
        id: 11,
        title: "深圳'岗课赛证'一体化育人模式",
        category: "vocational",
        country: "中国",
        description: "以岗位能力重塑课程体系，将技能大赛任务融入课堂，全面嵌入'1+X'证书模块，构建教师、企业、赛事协同的育人共同体。",
        impact: "学生竞赛获奖百余项，用人单位满意度超94%，毕业生三年内岗位晋升率超过40%",
        tags: ["岗课赛证", "校企合作", "1+X证书"],
        color: "blue",
        icon: "fas fa-certificate",
        stats: { satisfaction: 94, employment: 96, skillMatch: 88 }
    },
    {
        id: 12,
        title: "湖北教育数字化生态重塑",
        category: "digital",
        country: "中国",
        description: "作为国家智慧教育平台整省试点，通过AI、VR、数字孪生等技术构建'三维教育场'，实现个性化教学与优质资源跨区域共享。",
        impact: "多媒体教学设备100%覆盖，智慧教育平台用户活跃度全国前列，新技术转化教学内容时间缩短85%",
        tags: ["人工智能", "数字孪生", "教育公平"],
        color: "cyan",
        icon: "fas fa-laptop-code",
        stats: { satisfaction: 86, employment: 89, skillMatch: 82 }
    },
    {
        id: 13,
        title: "江苏新型小班制教学改革",
        category: "curriculum",
        country: "中国",
        description: "从'班额小'升级为'视角小'，开发丰富'适性课程'，实行'导师伴学制'与分层作业，推动教学从'大水漫灌'转向'精准滴灌'。",
        impact: "学生课程选择面和个性化关注度大幅增加，部分'草小'教学质量持续提升，成为家门口的优质校",
        tags: ["分层教学", "导师制", "个性化课程"],
        color: "purple",
        icon: "fas fa-user-graduate",
        stats: { satisfaction: 87, employment: 0, skillMatch: 80 }
    },
    {
        id: 14,
        title: "内蒙古包头集团化办学改革",
        category: "policy",
        country: "中国",
        description: "通过'名校+薄弱校/新建校'横向集群与跨学段纵向贯通，扩大优质资源覆盖面，并赋予集团校更多自主权，促进师资流动。",
        impact: "培育教育集团43个，覆盖300余所学校，惠及10万余名学生，有效缩小了城乡、校际差距",
        tags: ["集团化办学", "资源均衡", "师资流动"],
        color: "green",
        icon: "fas fa-landmark",
        stats: { satisfaction: 85, employment: 0, skillMatch: 75 }
    },
    {
        id: 15,
        title: "北京中关村人工智能教育试验区",
        category: "digital",
        country: "中国",
        description: "在中关村科技园区设立人工智能教育创新试验区，开发AI通识课程，建立中小学AI实验室，培养青少年人工智能素养。",
        impact: "建成50所AI教育示范校，培训教师5000余名，学生AI项目获国际奖项120余项",
        tags: ["人工智能", "科技教育", "创新试验区"],
        color: "cyan",
        icon: "fas fa-robot",
        stats: { satisfaction: 89, employment: 0, skillMatch: 84 }
    },
    {
        id: 16,
        title: "重庆职业教育'双师型'教师培养体系",
        category: "vocational",
        country: "中国",
        description: "构建'学校教师+企业技师'双向流动机制，实施教师企业实践学分制，建立'双师型'教师认证与激励机制。",
        impact: "'双师型'教师比例从35%提升至78%，企业技师兼职任教人数增长300%，教学实践性显著增强",
        tags: ["双师型教师", "企业实践", "教师培养"],
        color: "blue",
        icon: "fas fa-chalkboard-teacher",
        stats: { satisfaction: 86, employment: 93, skillMatch: 88 }
    },
    {
        id: 17,
        title: "广东粤港澳大湾区职业教育资格互认",
        category: "policy",
        country: "中国",
        description: "推动粤港澳三地职业教育标准对接，建立技能等级互认机制，实现职业资格证书跨境通用，促进人才自由流动。",
        impact: "实现12个职业领域资格互认，惠及5万名技能人才，大湾区技能人才流动便利度提升60%",
        tags: ["资格互认", "大湾区", "跨境流动"],
        color: "green",
        icon: "fas fa-handshake",
        stats: { satisfaction: 88, employment: 91, skillMatch: 86 }
    },
    {
        id: 18,
        title: "山东农村小规模学校整合优化",
        category: "basic",
        country: "中国",
        description: "科学规划农村学校布局，合并规模过小学校，优化教育资源分配，通过'中心校+教学点'模式提升农村教育质量。",
        impact: "农村学校生均经费提高50%，教师专业发展机会增加，学生学业成绩平均提升22%",
        tags: ["农村教育", "学校整合", "资源优化"],
        color: "orange",
        icon: "fas fa-school",
        stats: { satisfaction: 82, employment: 0, skillMatch: 78 }
    },
    {
        id: 19,
        title: "四川民族地区'9+3'免费职业教育",
        category: "vocational",
        country: "中国",
        description: "为民族地区初中毕业生提供3年免费中职教育，实行'双语教学+技能培训+文化适应'融合模式，促进就业与社会融合。",
        impact: "累计培养少数民族技能人才8万余人，就业率达96%，家庭脱贫率超过70%",
        tags: ["民族教育", "免费职教", "就业扶贫"],
        color: "blue",
        icon: "fas fa-users",
        stats: { satisfaction: 90, employment: 96, skillMatch: 85 }
    },
    {
        id: 20,
        title: "福建'数字公民'素养教育计划",
        category: "digital",
        country: "中国",
        description: "将数字素养教育纳入中小学必修课程，系统培养信息辨识、网络安全、数字伦理和编程思维等核心能力。",
        impact: "数字素养课程覆盖率100%，学生网络信息安全意识测评优秀率达85%，青少年编程大赛获奖数翻番",
        tags: ["数字素养", "网络安全", "编程教育"],
        color: "cyan",
        icon: "fas fa-shield-alt",
        stats: { satisfaction: 87, employment: 0, skillMatch: 83 }
    },
    {
        id: 21,
        title: "陕西革命老区红色研学旅行课程",
        category: "curriculum",
        country: "中国",
        description: "开发融合革命历史、地理考察和社会实践的红色研学课程体系，将爱国主义教育融入体验式学习。",
        impact: "建成30条红色研学精品路线，年接待学生100万人次，学生爱国主义情怀测评满意度达95%",
        tags: ["研学旅行", "红色教育", "实践课程"],
        color: "purple",
        icon: "fas fa-monument",
        stats: { satisfaction: 92, employment: 0, skillMatch: 79 }
    },
    {
        id: 22,
        title: "浙江特色普通高中分类发展改革",
        category: "policy",
        country: "中国",
        description: "推动普通高中从'分层'转向'分类'发展，建设科技、人文、艺术、体育等特色高中，满足学生多样化发展需求。",
        impact: "建成150所特色示范高中，学生根据兴趣选课比例从30%提升至75%，升学路径更加多元",
        tags: ["特色高中", "分类发展", "多样化"],
        color: "green",
        icon: "fas fa-palette",
        stats: { satisfaction: 88, employment: 87, skillMatch: 82 }
    },
    {
        id: 23,
        title: "湖南'芙蓉学校'教育扶贫工程",
        category: "basic",
        country: "中国",
        description: "在贫困县集中建设一批标准化寄宿制'芙蓉学校'，通过优质师资定向输送和数字资源共享，阻断贫困代际传递。",
        impact: "建成101所芙蓉学校，惠及贫困地区学生15万人，学业成绩与城区学校差距缩小40%",
        tags: ["教育扶贫", "标准化建设", "资源均衡"],
        color: "orange",
        icon: "fas fa-hands-helping",
        stats: { satisfaction: 91, employment: 0, skillMatch: 80 }
    },
    {
        id: 24,
        title: "天津职业教育'鲁班工坊'海外推广",
        category: "vocational",
        country: "中国",
        description: "将中国职业教育标准与装备整体输出，在'一带一路'沿线国家建设'鲁班工坊'，培养当地技术技能人才。",
        impact: "在20个国家建成30个鲁班工坊，培训海外学员1万余名，中国职教标准获国际广泛认可",
        tags: ["鲁班工坊", "一带一路", "标准输出"],
        color: "blue",
        icon: "fas fa-globe-asia",
        stats: { satisfaction: 89, employment: 90, skillMatch: 87 }
    },
    {
        id: 25,
        title: "河南'互联网+教育'精准扶贫",
        category: "digital",
        country: "中国",
        description: "利用互联网平台将优质课程资源输送到贫困地区学校，通过双师课堂、在线辅导缩小城乡教育差距。",
        impact: "覆盖3000所农村薄弱学校，受益学生200万人，农村学生学业合格率提升25个百分点",
        tags: ["互联网+", "教育扶贫", "双师课堂"],
        color: "cyan",
        icon: "fas fa-satellite-dish",
        stats: { satisfaction: 85, employment: 0, skillMatch: 81 }
    },
    {
        id: 26,
        title: "云南边境国门学校建设工程",
        category: "basic",
        country: "中国",
        description: "在边境县市建设标准化'国门学校'，改善边境地区办学条件，增强国家认同感和边疆教育吸引力。",
        impact: "建成374所国门学校，边境地区学生巩固率达99.5%，跨境就学外籍学生超过1万人",
        tags: ["边境教育", "国门学校", "国家认同"],
        color: "orange",
        icon: "fas fa-flag",
        stats: { satisfaction: 90, employment: 0, skillMatch: 77 }
    },
    {
        id: 27,
        title: "辽宁老工业基地技能转型培训计划",
        category: "vocational",
        country: "中国",
        description: "针对传统产业工人开展大规模技能提升和转岗培训，聚焦智能制造、新能源等新兴领域，助力产业转型升级。",
        impact: "培训产业工人50万人次，再就业率达85%，企业劳动生产率平均提升30%",
        tags: ["技能转型", "产业工人", "再培训"],
        color: "blue",
        icon: "fas fa-cogs",
        stats: { satisfaction: 84, employment: 85, skillMatch: 83 }
    },
    {
        id: 28,
        title: "安徽高校创新创业教育生态系统",
        category: "curriculum",
        country: "中国",
        description: "构建'课程教学+实践训练+孵化支持'三位一体的创新创业教育体系，将双创教育深度融入专业人才培养全过程。",
        impact: "学生创业参与率从5%提升至25%，毕业生创业存活三年以上比例达40%，创造就业岗位5万余个",
        tags: ["创新创业", "生态系统", "实践训练"],
        color: "purple",
        icon: "fas fa-rocket",
        stats: { satisfaction: 86, employment: 88, skillMatch: 84 }
    },
    {
        id: 29,
        title: "贵州大数据人才产教融合培养",
        category: "digital",
        country: "中国",
        description: "依托国家大数据综合试验区，建立政校企协同的大数据人才培养机制，实施'订单式'培养和'项目化'教学。",
        impact: "为大数据产业输送专业人才3万余人，本地就业率达92%，企业满意度超过90%",
        tags: ["大数据", "产教融合", "订单培养"],
        color: "cyan",
        icon: "fas fa-database",
        stats: { satisfaction: 90, employment: 92, skillMatch: 89 }
    },
    {
        id: 30,
        title: "甘肃农村教师特岗计划升级版",
        category: "policy",
        country: "中国",
        description: "扩大农村教师特岗计划规模，提高待遇保障，建立'县管校聘'管理机制，稳定和优化农村教师队伍。",
        impact: "年均补充农村教师5000名，特岗教师留任率从60%提升至85%，农村学校师资结构性短缺有效缓解",
        tags: ["特岗计划", "农村教师", "县管校聘"],
        color: "green",
        icon: "fas fa-chalkboard-teacher",
        stats: { satisfaction: 83, employment: 0, skillMatch: 79 }
    },
    {
        id: 31,
        title: "海南国际教育创新岛建设",
        category: "policy",
        country: "中国",
        description: "在海南自由贸易港框架下，引进国内外优质教育资源，建设国际教育创新岛，打造教育改革开放新高地。",
        impact: "引进国内外知名高校20余所，在校国际学生数量增长300%，教育服务贸易额突破10亿元",
        tags: ["国际教育", "自由贸易港", "教育开放"],
        color: "green",
        icon: "fas fa-university",
        stats: { satisfaction: 87, employment: 89, skillMatch: 82 }
    },
    {
        id: 32,
        title: "山西煤炭行业转岗职工技能重塑",
        category: "vocational",
        country: "中国",
        description: "针对煤炭去产能过程中的转岗职工，开展定制化技能培训，重点向文化旅游、现代农业、服务业等领域转型。",
        impact: "培训转岗职工8万余人，再就业率达82%，家庭收入恢复或超过原有水平比例达75%",
        tags: ["转岗培训", "煤炭行业", "技能重塑"],
        color: "blue",
        icon: "fas fa-hard-hat",
        stats: { satisfaction: 82, employment: 82, skillMatch: 80 }
    },
    {
        id: 33,
        title: "吉林冰雪运动特色学校建设",
        category: "curriculum",
        country: "中国",
        description: "将冰雪运动纳入学校体育课程，建设校园冰场、滑雪模拟设施，培养青少年冰雪运动技能和兴趣爱好。",
        impact: "建成冰雪运动特色学校500所，学生冰雪运动参与率从10%提升至60%，为国家队输送后备人才200余人",
        tags: ["冰雪运动", "特色学校", "体育课程"],
        color: "purple",
        icon: "fas fa-snowflake",
        stats: { satisfaction: 89, employment: 0, skillMatch: 76 }
    },
    {
        id: 34,
        title: "青海生态教育课程体系开发",
        category: "curriculum",
        country: "中国",
        description: "结合三江源生态保护区特点，开发涵盖生态知识、环保技能和可持续发展观的本地化生态教育课程。",
        impact: "生态教育覆盖全省中小学，学生环保行为养成率达90%，带动家庭参与环保实践比例超过70%",
        tags: ["生态教育", "三江源", "可持续发展"],
        color: "purple",
        icon: "fas fa-leaf",
        stats: { satisfaction: 88, employment: 0, skillMatch: 78 }
    },
    {
        id: 35,
        title: "西藏自治区国家通用语言文字普及攻坚",
        category: "basic",
        country: "中国",
        description: "通过教师专项培训、双语教材优化和语言实践环境营造，全面提升少数民族学生国家通用语言文字能力。",
        impact: "中小学生国家通用语言文字达标率从75%提升至95%，高等教育入学率提高20个百分点",
        tags: ["国家通用语言", "双语教育", "语言普及"],
        color: "orange",
        icon: "fas fa-language",
        stats: { satisfaction: 86, employment: 0, skillMatch: 81 }
    },
    {
        id: 36,
        title: "宁夏'互联网+职业教育'智慧校园",
        category: "digital",
        country: "中国",
        description: "建设覆盖全区职业院校的智慧教育平台，实现虚拟仿真实训、远程协作教学和技能大数据分析。",
        impact: "建成50所智慧校园示范校，虚拟仿真实训使用率达80%，学生技能掌握效率提升40%",
        tags: ["智慧校园", "虚拟实训", "职业教育"],
        color: "cyan",
        icon: "fas fa-brain",
        stats: { satisfaction: 87, employment: 90, skillMatch: 85 }
    },
    {
        id: 37,
        title: "新疆维吾尔自治区职业技能大赛体系",
        category: "vocational",
        country: "中国",
        description: "建立覆盖地区、县市、学校的三级职业技能竞赛体系，以赛促学、以赛促教，提升技能人才培养质量。",
        impact: "年均举办技能大赛1000余场，参赛学生超过10万人次，国赛获奖数增长300%",
        tags: ["技能大赛", "以赛促学", "竞赛体系"],
        color: "blue",
        icon: "fas fa-trophy",
        stats: { satisfaction: 89, employment: 91, skillMatch: 86 }
    },
    {
        id: 38,
        title: "黑龙江对俄教育合作交流平台",
        category: "policy",
        country: "中国",
        description: "依托地缘优势，建设中俄高校联盟、联合实验室和师生交流项目，打造对俄教育合作先行区。",
        impact: "与俄罗斯80余所高校建立合作关系，联合培养项目在校生达5000人，对俄教育合作项目数全国第一",
        tags: ["对俄合作", "教育交流", "高校联盟"],
        color: "green",
        icon: "fas fa-handshake",
        stats: { satisfaction: 85, employment: 87, skillMatch: 80 }
    },
    {
        id: 39,
        title: "江西红色基因传承主题教育",
        category: "curriculum",
        country: "中国",
        description: "系统挖掘本地红色教育资源，开发系列红色校本课程，将红色基因传承融入教育教学全过程。",
        impact: "开发红色校本课程1000余门，建设红色教育基地200个，学生红色文化认知测评优秀率达90%",
        tags: ["红色基因", "校本课程", "主题教育"],
        color: "purple",
        icon: "fas fa-history",
        stats: { satisfaction: 90, employment: 0, skillMatch: 79 }
    },
    {
        id: 40,
        title: "广西面向东盟的职业教育合作",
        category: "vocational",
        country: "中国",
        description: "发挥毗邻东盟优势，开发东盟小语种+职业技能复合型人才培养项目，服务中国-东盟区域经济合作。",
        impact: "开设东盟小语种专业15个，培养复合型人才1万余人，毕业生在东盟国家就业率达30%",
        tags: ["东盟合作", "小语种", "复合型人才"],
        color: "blue",
        icon: "fas fa-globe-asia",
        stats: { satisfaction: 88, employment: 85, skillMatch: 84 }
    },
    {
        id: 41,
        title: "澳门'旅游+教育'融合发展模式",
        category: "curriculum",
        country: "中国",
        description: "结合澳门世界旅游休闲中心定位，开发融合旅游管理、文化遗产、服务技能的专业课程体系。",
        impact: "旅游相关专业学生占比达40%，毕业生本地就业率95%，为旅游业升级提供人才支撑",
        tags: ["旅游教育", "融合发展", "文化遗产"],
        color: "purple",
        icon: "fas fa-umbrella-beach",
        stats: { satisfaction: 91, employment: 95, skillMatch: 88 }
    },
    {
        id: 42,
        title: "香港STEAM教育推广计划",
        category: "curriculum",
        country: "中国",
        description: "在中小学全面推广科学、技术、工程、艺术和数学融合的STEAM教育，培养学生创新思维和问题解决能力。",
        impact: "STEAM教育覆盖全港中小学，学生国际创新大赛获奖数增长200%，科技创新素养显著提升",
        tags: ["STEAM教育", "创新思维", "跨学科"],
        color: "purple",
        icon: "fas fa-atom",
        stats: { satisfaction: 87, employment: 0, skillMatch: 85 }
    },
    {
        id: 43,
        title: "台湾地区社区大学终身学习网络",
        category: "policy",
        country: "中国",
        description: "建立覆盖城乡的社区大学体系，提供多样化、低门槛的终身学习课程，促进学习型社会建设。",
        impact: "社区大学达100余所，年参与学习人次超过200万，中高龄学习者比例达40%",
        tags: ["社区大学", "终身学习", "学习型社会"],
        color: "green",
        icon: "fas fa-graduation-cap",
        stats: { satisfaction: 89, employment: 0, skillMatch: 78 }
    },
    {
        id: 44,
        title: "河北雄安新区未来教育实验区",
        category: "policy",
        country: "中国",
        description: "在雄安新区高起点规划建设未来学校，探索人工智能、大数据等技术深度融合的教育新模式。",
        impact: "规划建设未来学校30所，引入创新教育项目50余个，打造全国教育改革创新样板",
        tags: ["雄安新区", "未来学校", "教育实验"],
        color: "green",
        icon: "fas fa-city",
        stats: { satisfaction: 88, employment: 0, skillMatch: 86 }
    },
    {
        id: 45,
        title: "湖北武汉光谷科创教育走廊",
        category: "digital",
        country: "中国",
        description: "依托光谷科技创新资源，建设校内外联动的科创教育生态，将前沿科技项目转化为青少年学习体验。",
        impact: "建成科创教育基地50个，开发科创课程200门，学生科技创新成果获专利授权100余项",
        tags: ["科创教育", "光谷", "创新生态"],
        color: "cyan",
        icon: "fas fa-microchip",
        stats: { satisfaction: 90, employment: 0, skillMatch: 87 }
    },
    
    // ========== 新增国外案例 (ID 46-75) ==========
    {
        id: 46,
        title: "瑞士职业教育和培训（VET）体系",
        category: "vocational",
        country: "瑞士",
        description: "全球公认的黄金标准，约三分之二的初中毕业生选择进入VET体系。采用'双轨制'，学生在企业当学徒，同时在职业学校学习理论知识。",
        impact: "青年失业率长期维持在5%以下，确保了经济各领域拥有稳定、高素质的技能人才供应，企业参与度超过90%",
        tags: ["双轨制", "企业主导", "全国标准"],
        color: "blue",
        icon: "fas fa-user-tie",
        stats: { satisfaction: 95, employment: 96, skillMatch: 93 }
    },
    {
        id: 47,
        title: "美国High Tech High项目式学习网络",
        category: "curriculum",
        country: "美国",
        description: "完全取消传统学科分隔，所有学习围绕跨学科、真实世界的长期项目展开，学生通过公开展示作品来完成学业评价。",
        impact: "项目学校的学生，尤其是来自低收入家庭的学生，在大学持续深造率和毕业率上显著高于地区平均水平",
        tags: ["项目式学习", "跨学科", "作品评价"],
        color: "purple",
        icon: "fas fa-project-diagram",
        stats: { satisfaction: 91, employment: 88, skillMatch: 87 }
    },
    {
        id: 48,
        title: "芬兰基于信任的教师专业自主模式",
        category: "policy",
        country: "芬兰",
        description: "国家仅提供宽松的课程框架，教师拥有极大的教学设计与教材选择自主权。其基础是经过严格筛选和高质量硕士层次培养的教师队伍。",
        impact: "在PISA等国际评估中持续名列前茅，同时学生学习幸福感强、课时短，形成了'高质量、低压力'的独特教育生态",
        tags: ["教师自主", "专业信任", "高质量培养"],
        color: "green",
        icon: "fas fa-chalkboard-teacher",
        stats: { satisfaction: 96, employment: 92, skillMatch: 89 }
    },
    {
        id: 49,
        title: "英国学徒制改革与学位学徒计划",
        category: "vocational",
        country: "英国",
        description: "建立由雇主主导的学徒标准，引入学位学徒制，实现高等教育与职业教育的深度融合，学徒可获得学士甚至硕士学位。",
        impact: "学徒参与人数增长65%，雇主满意度达84%，学位学徒毕业生起薪比传统大学毕业生高15%",
        tags: ["学徒制", "学位学徒", "雇主主导"],
        color: "blue",
        icon: "fas fa-user-graduate",
        stats: { satisfaction: 84, employment: 93, skillMatch: 88 }
    },
    {
        id: 50,
        title: "丹麦终身学习账户制度",
        category: "policy",
        country: "丹麦",
        description: "为每位公民设立终身学习个人账户，政府与企业共同注资，个人可自主选择学习内容与时间，实现真正的终身学习。",
        impact: "成人参与终身学习比例达72%，技能更新周期缩短40%，劳动力市场适应性显著提升",
        tags: ["终身学习", "个人账户", "技能更新"],
        color: "green",
        icon: "fas fa-piggy-bank",
        stats: { satisfaction: 89, employment: 91, skillMatch: 85 }
    },
    {
        id: 51,
        title: "以色列创新教育生态系统",
        category: "curriculum",
        country: "以色列",
        description: "从基础教育阶段引入创新思维与方法论教学，建立学校-企业-军方多元协同的创新人才培养体系。",
        impact: "每百万人口科技创业数量全球第一，青少年科技创新大赛获奖数连续多年位居世界前列",
        tags: ["创新思维", "生态系统", "创业教育"],
        color: "purple",
        icon: "fas fa-rocket",
        stats: { satisfaction: 90, employment: 87, skillMatch: 83 }
    },
    {
        id: 52,
        title: "新西兰土著文化融入基础教育",
        category: "basic",
        country: "新西兰",
        description: "将毛利文化、语言与传统知识系统融入国家课程体系，建立文化响应式教学框架，促进多元文化理解与尊重。",
        impact: "毛利学生学业完成率提升45%，文化认同感显著增强，跨文化理解能力测评优秀率78%",
        tags: ["文化响应", "土著教育", "多元文化"],
        color: "orange",
        icon: "fas fa-globe-asia",
        stats: { satisfaction: 87, employment: 82, skillMatch: 80 }
    },
    {
        id: 53,
        title: "爱沙尼亚数字公民教育",
        category: "digital",
        country: "爱沙尼亚",
        description: "从小学一年级开始系统实施数字素养教育，将编程思维、网络安全、数字伦理融入各学科，培养数字时代合格公民。",
        impact: "数字素养国际测评位居欧盟第一，99%的公共服务可在线完成，成为全球数字化程度最高的国家之一",
        tags: ["数字素养", "编程教育", "数字公民"],
        color: "cyan",
        icon: "fas fa-shield-alt",
        stats: { satisfaction: 88, employment: 90, skillMatch: 87 }
    },
    {
        id: 54,
        title: "法国高中教育改革与专业分科优化",
        category: "curriculum",
        country: "法国",
        description: "取消传统文理分科，引入跨学科教学模块，增加学生课程选择自主权，强化通用能力培养。",
        impact: "学生专业满意度提升40%，跨学科能力测评提升32%，高考改革平稳实施",
        tags: ["高中改革", "专业分科", "跨学科"],
        color: "purple",
        icon: "fas fa-university",
        stats: { satisfaction: 82, employment: 85, skillMatch: 79 }
    },
    {
        id: 55,
        title: "印度技能印度使命计划",
        category: "vocational",
        country: "印度",
        description: "通过公私合作模式大规模开展技能培训，建立行业驱动的技能标准与认证体系，重点面向青年与弱势群体。",
        impact: "累计培训超过1.2亿人，青年就业率提升22%，技能认证覆盖率从15%提升至65%",
        tags: ["技能培训", "公私合作", "大规模实施"],
        color: "blue",
        icon: "fas fa-hands-helping",
        stats: { satisfaction: 79, employment: 84, skillMatch: 76 }
    },
    {
        id: 56,
        title: "巴西'全民技术赋能开放学校'试点[citation:3]",
        category: "digital",
        country: "巴西",
        description: "通过搭建数字基础设施、推广可再生能源应用、开展教师专业培训，为资源匮乏地区学校注入科技动能，助力教育数字化转型与公平优质教育普及[citation:3]。",
        impact: "为试点学校配备通信基础设施和太阳能发电系统，构建完整数字化教学环境，预计培训1000名教师和学生[citation:3]",
        tags: ["数字包容", "开放学校", "可持续发展"],
        color: "cyan",
        icon: "fas fa-solar-panel",
        stats: { satisfaction: 83, employment: 0, skillMatch: 78 }
    },
    {
        id: 57,
        title: "瑞典平等导向的教育政策",
        category: "policy",
        country: "瑞典",
        description: "通过资源倾斜、个性化支持、全纳教育等措施，系统性减少家庭背景对学生学业成就的影响。",
        impact: "教育基尼系数在OECD国家中最低，弱势家庭学生高等教育入学率接近全国平均水平",
        tags: ["教育平等", "全纳教育", "资源倾斜"],
        color: "green",
        icon: "fas fa-balance-scale",
        stats: { satisfaction: 85, employment: 88, skillMatch: 82 }
    },
    {
        id: 58,
        title: "阿联酋人工智能教育战略",
        category: "digital",
        country: "阿联酋",
        description: "在国家层面实施人工智能教育战略，将AI课程纳入K-12教育体系，培养面向未来的人工智能人才。",
        impact: "成为中东地区AI教育领先国家，学生AI素养测评优秀率62%，相关领域大学申请人数增长300%",
        tags: ["人工智能", "国家战略", "未来技能"],
        color: "cyan",
        icon: "fas fa-robot",
        stats: { satisfaction: 86, employment: 91, skillMatch: 84 }
    },
    {
        id: 59,
        title: "南非职业教育学院改革",
        category: "vocational",
        country: "南非",
        description: "重组职业教育学院体系，强化行业咨询委员会作用，引入工作本位学习模式，提高职业教育吸引力与质量。",
        impact: "职业学院毕业生就业率从35%提升至68%，企业参与职业教育比例增长120%",
        tags: ["学院改革", "工作本位", "行业参与"],
        color: "blue",
        icon: "fas fa-hard-hat",
        stats: { satisfaction: 77, employment: 68, skillMatch: 72 }
    },
    {
        id: 60,
        title: "墨西哥社区参与式学校管理",
        category: "basic",
        country: "墨西哥",
        description: "建立社区参与学校决策与管理的制度框架，家长与社区代表直接参与学校预算、人事与课程决策。",
        impact: "社区对学校满意度从45%提升至82%，学生辍学率下降30%，学校资源使用效率提高",
        tags: ["社区参与", "学校管理", "家长赋权"],
        color: "orange",
        icon: "fas fa-users",
        stats: { satisfaction: 82, employment: 0, skillMatch: 75 }
    },
    {
        id: 61,
        title: "爱尔兰语言复兴与教育融合",
        category: "curriculum",
        country: "爱尔兰",
        description: "通过沉浸式语言教育、文化融入课程、数字化学习资源等措施，系统性复兴爱尔兰语并增强文化认同。",
        impact: "能流利使用爱尔兰语的人口比例从10%提升至25%，语言学习兴趣显著增强",
        tags: ["语言复兴", "文化认同", "沉浸式教学"],
        color: "purple",
        icon: "fas fa-language",
        stats: { satisfaction: 84, employment: 83, skillMatch: 80 }
    },
    {
        id: 62,
        title: "智利教师职业发展阶梯体系",
        category: "policy",
        country: "智利",
        description: "建立基于绩效与专业发展的教师职业阶梯，将薪酬、职责与发展机会与专业成长阶段挂钩。",
        impact: "教师职业吸引力提升50%，优秀教师流失率下降35%，课堂教学质量显著改善",
        tags: ["教师发展", "职业阶梯", "绩效激励"],
        color: "green",
        icon: "fas fa-chalkboard-teacher",
        stats: { satisfaction: 83, employment: 0, skillMatch: 81 }
    },
    {
        id: 63,
        title: "马来西亚数字教育转型计划",
        category: "digital",
        country: "马来西亚",
        description: "全面升级学校数字基础设施，为教师提供数字教学能力培训，开发本土化数字学习资源与平台。",
        impact: "数字课堂覆盖率从40%提升至92%，教师数字教学能力达标率85%，偏远地区学生受益明显",
        tags: ["数字转型", "基础设施", "教师培训"],
        color: "cyan",
        icon: "fas fa-satellite-dish",
        stats: { satisfaction: 84, employment: 86, skillMatch: 82 }
    },
    {
        id: 64,
        title: "奥地利双元制高等教育",
        category: "vocational",
        country: "奥地利",
        description: "将双元制模式延伸至高等教育领域，应用科学大学与企业深度合作，培养高层次应用型人才。",
        impact: "双元制大学生毕业时已有平均2年工作经验，就业率98%，企业满意度91%",
        tags: ["双元制", "高等教育", "应用型人才"],
        color: "blue",
        icon: "fas fa-user-tie",
        stats: { satisfaction: 91, employment: 98, skillMatch: 94 }
    },
    {
        id: 65,
        title: "挪威户外教育国家课程",
        category: "basic",
        country: "挪威",
        description: "将户外教育正式纳入国家课程标准，规定各年级学生每年必须完成的户外学习时间与内容。",
        impact: "学生身心健康指标显著改善，环境意识与团队合作能力测评优秀率超过90%",
        tags: ["户外教育", "身心健康", "环境意识"],
        color: "orange",
        icon: "fas fa-tree",
        stats: { satisfaction: 93, employment: 0, skillMatch: 85 }
    },
    {
        id: 66,
        title: "泰国职业教育4.0改革",
        category: "vocational",
        country: "泰国",
        description: "对接国家4.0战略，改造传统职业教育专业，增设数字经济、机器人、生物技术等前沿领域课程。",
        impact: "新兴产业相关专业毕业生就业率达96%，起薪比传统专业高40%，企业定制培养订单增长300%",
        tags: ["工业4.0", "新兴产业", "专业改造"],
        color: "blue",
        icon: "fas fa-cogs",
        stats: { satisfaction: 88, employment: 96, skillMatch: 90 }
    },
    {
        id: 67,
        title: "葡萄牙学校自主权下放改革",
        category: "policy",
        country: "葡萄牙",
        description: "将课程安排、教师招聘、预算使用等权限下放至学校层面，增强学校应对本地需求的灵活性与创新性。",
        impact: "学校创新项目数量增长200%，家长与社区满意度提升40%，教育资源使用效率提高",
        tags: ["学校自主", "权限下放", "地方适应"],
        color: "green",
        icon: "fas fa-unlock",
        stats: { satisfaction: 82, employment: 0, skillMatch: 79 }
    },
    {
        id: 68,
        title: "越南农村地区教育数字化转型",
        category: "digital",
        country: "越南",
        description: "针对农村地区实施专项数字教育计划，提供设备补贴、网络接入、本地化数字内容与教师培训。",
        impact: "农村学校数字设备覆盖率从25%提升至85%，数字资源使用率增长400%，城乡数字教育差距缩小",
        tags: ["农村教育", "数字包容", "专项计划"],
        color: "cyan",
        icon: "fas fa-tractor",
        stats: { satisfaction: 83, employment: 81, skillMatch: 78 }
    },
    {
        id: 69,
        title: "波兰历史与公民教育改革",
        category: "curriculum",
        country: "波兰",
        description: "重新设计历史与公民教育课程，强化批判性思维、民主价值观与民族认同教育。",
        impact: "学生公民素养测评提升35%，历史理解深度显著改善，民主价值观认同度达88%",
        tags: ["公民教育", "历史教育", "批判性思维"],
        color: "purple",
        icon: "fas fa-monument",
        stats: { satisfaction: 79, employment: 0, skillMatch: 76 }
    },
    {
        id: 70,
        title: "阿根廷教师合作学习网络",
        category: "policy",
        country: "阿根廷",
        description: "建立全国性教师专业学习社群，鼓励跨校合作、经验分享与集体备课，减少教师专业孤立。",
        impact: "教师专业满意度提升45%，教学创新实践分享增长300%，新教师适应期缩短60%",
        tags: ["教师合作", "学习网络", "专业社群"],
        color: "green",
        icon: "fas fa-network-wired",
        stats: { satisfaction: 87, employment: 0, skillMatch: 82 }
    },
    {
        id: 71,
        title: "菲律宾K-12课程体系改革",
        category: "curriculum",
        country: "菲律宾",
        description: "将基础教育从10年延长至12年，新增两年高中教育，强化学术、技术与生活技能的平衡培养。",
        impact: "高中生毕业准备度提升50%，高等教育适应度改善40%，国际学历认可度大幅提高",
        tags: ["K-12", "课程延长", "技能平衡"],
        color: "purple",
        icon: "fas fa-layer-group",
        stats: { satisfaction: 78, employment: 82, skillMatch: 80 }
    },
    {
        id: 72,
        title: "肯尼亚移动学习创新项目",
        category: "digital",
        country: "肯尼亚",
        description: "利用移动电话普及率高的优势，开发短信、语音与轻量级App学习平台，为偏远地区学生提供学习支持。",
        impact: "偏远地区学生学业完成率提升30%，学习资源可及性改善80%，成本仅为传统数字方案的20%",
        tags: ["移动学习", "低成本", "普惠教育"],
        color: "cyan",
        icon: "fas fa-mobile-alt",
        stats: { satisfaction: 85, employment: 80, skillMatch: 77 }
    },
    {
        id: 73,
        title: "希腊职业教育国际化战略",
        category: "vocational",
        country: "希腊",
        description: "推动职业教育课程与欧盟资格框架对接，加强跨国企业合作，为学生提供欧盟内实习与就业机会。",
        impact: "职业教育毕业生欧盟内就业率从15%提升至45%，跨国企业合作项目增长200%",
        tags: ["国际化", "欧盟框架", "跨国就业"],
        color: "blue",
        icon: "fas fa-passport",
        stats: { satisfaction: 82, employment: 85, skillMatch: 83 }
    },
    {
        id: 74,
        title: "马拉维BEFIT平板教育项目[citation:9]",
        category: "digital",
        country: "马拉维",
        description: "通过'Building Education Foundations through Innovation & Technology'项目，为小学提供平板电脑，提供个性化的识字和计算课程[citation:9]。",
        impact: "首年为500所学校、27.7万名学生提供服务，计划覆盖全国所有小学，显著提升基础学习效果[citation:9]",
        tags: ["平板教育", "基础学习", "个性化"],
        color: "cyan",
        icon: "fas fa-tablet-alt",
        stats: { satisfaction: 84, employment: 0, skillMatch: 79 }
    },
    {
        id: 75,
        title: "夏威夷学校创新与赋权蓝图[citation:5]",
        category: "policy",
        country: "美国",
        description: "制定'夏威夷公立学校蓝图'，赋予学校更多资源控制权，推动早期大学计划，建立全州范围的公立学前教育系统[citation:5]。",
        impact: "早期大学计划扩展至43所公立高中，为社区学院提供资金支持，完成1300间教室降温改造[citation:5]",
        tags: ["学校赋权", "早期大学", "学前教育"],
        color: "green",
        icon: "fas fa-blueprint",
        stats: { satisfaction: 86, employment: 0, skillMatch: 81 }
    }
];

// 案例数据统计信息
const casesStats = {
    total: casesData.length,
    byCategory: {
        vocational: casesData.filter(c => c.category === 'vocational').length,
        basic: casesData.filter(c => c.category === 'basic').length,
        curriculum: casesData.filter(c => c.category === 'curriculum').length,
        policy: casesData.filter(c => c.category === 'policy').length,
        digital: casesData.filter(c => c.category === 'digital').length
    },
    byCountry: {
        china: casesData.filter(c => c.country === '中国').length,
        international: casesData.filter(c => c.country !== '中国').length
    }
};

// 控制台输出统计信息（开发时有用）
console.log(`案例库已加载：共${casesStats.total}个案例`);
console.log('分类统计：', casesStats.byCategory);
console.log('地域统计：中国案例', casesStats.byCountry.china, '个，国际案例', casesStats.byCountry.international, '个');

// 导出案例数据（如果使用模块系统）
// export { casesData, casesStats };
